version: 8
groups: []
configSync:
  parts: {}
hotkeys:
  toggle-window:
    - Ctrl-Space
  copy-current-path: []
  ctrl-c:
    - Ctrl-C
  copy:
    - Ctrl-Shift-C
  paste:
    - Ctrl-Shift-V
    - Shift-Insert
  select-all:
    - Ctrl-Shift-A
  clear: []
  zoom-in:
    - Ctrl-=
    - Ctrl-Shift-=
  zoom-out:
    - Ctrl--
    - Ctrl-Shift--
  reset-zoom:
    - Ctrl-0
  home:
    - Home
  end:
    - End
  previous-word:
    - Ctrl-Left
  next-word:
    - Ctrl-Right
  delete-previous-word:
    - Ctrl-Backspace
  delete-line:
    - Ctrl-Shift-Backspace
  delete-next-word:
    - Ctrl-Delete
  search:
    - Ctrl-Shift-F
  pane-focus-all:
    - Ctrl-Shift-I
  focus-all-tabs:
    - Ctrl-Alt-Shift-I
  scroll-to-top:
    - Ctrl-PageUp
  scroll-page-up:
    - Alt-PageUp
  scroll-up:
    - Ctrl-Shift-Up
  scroll-down:
    - Ctrl-Shift-Down
  scroll-page-down:
    - Alt-PageDown
  scroll-to-bottom:
    - Ctrl-PageDown
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings-tab:
    qc:
      - Alt-Shift-,
  settings:
    - Ctrl-,
  serial:
    - Alt-K
  restart-serial-session: []
  new-tab:
    - Ctrl-Shift-T
  new-window:
    - Ctrl-Shift-N
  profile: {}
  profile-selectors: {}
  group-selectors: {}
  toggle-fullscreen:
    - F11
    - Alt-Enter
  close-tab:
    - Ctrl-Shift-W
  reopen-tab:
    - Ctrl-Shift-Z
  toggle-last-tab: []
  rename-tab:
    - Ctrl-Shift-R
  next-tab:
    - Ctrl-Shift-Right
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Left
    - Ctrl-Shift-Tab
  move-tab-left:
    - Ctrl-Shift-PageUp
  move-tab-right:
    - Ctrl-Shift-PageDown
  rearrange-panes:
    - Ctrl-Shift
  duplicate-tab: []
  restart-tab: []
  reconnect-tab: []
  disconnect-tab: []
  explode-tab:
    - Ctrl-Shift-.
  combine-tabs:
    - Ctrl-Shift-,
  tab-1:
    - Alt-1
  tab-2:
    - Alt-2
  tab-3:
    - Alt-3
  tab-4:
    - Alt-4
  tab-5:
    - Alt-5
  tab-6:
    - Alt-6
  tab-7:
    - Alt-7
  tab-8:
    - Alt-8
  tab-9:
    - Alt-9
  tab-10:
    - Alt-0
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - Ctrl-Shift-S
  split-bottom:
    - Ctrl-Shift-D
  split-left: []
  split-top: []
  pane-nav-right:
    - Ctrl-Alt-Right
  pane-nav-down:
    - Ctrl-Alt-Down
  pane-nav-up:
    - Ctrl-Alt-Up
  pane-nav-left:
    - Ctrl-Alt-Left
  pane-nav-previous:
    - Ctrl-Alt-[
  pane-nav-next:
    - Ctrl-Alt-]
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-maximize:
    - Ctrl-Alt-Enter
  close-pane: []
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal:
    - Alt-Shift-=
  pane-decrease-horizontal:
    - Alt-Shift--
  switch-profile:
    - Ctrl-Alt-T
  profile-selector:
    - Ctrl-Shift-E
  command-selector:
    - Ctrl-Shift-P
  qc:
    - Alt-Q
  workspace-profile-1:
    - Alt-W-1
  workspace-profile-2: []
  workspace-profile-3: []
  workspace-profile-4: []
  workspace-profile-5: []
  shift-enter-newline:
    - Shift-Enter
  qs:
    - Alt-S
  quick-restart:
    - Ctrl-R
  ogautocomplete_stop: []
  ogautocomplete_dev: []
  ogautocomplete_init_scripts: []
  ogautocomplete_ask_ai: []
  ogautocomplete_hint_now: []
terminal:
  searchOptions: {}
  colorScheme:
    name: TokyoNight
    foreground: '#c0caf5'
    background: '#1a1b26'
    cursor: '#c0caf5'
    colors:
      - '#15161e'
      - '#f7768e'
      - '#9ece6a'
      - '#e0af68'
      - '#7aa2f7'
      - '#bb9af7'
      - '#7dcfff'
      - '#a9b1d6'
      - '#414868'
      - '#f7768e'
      - '#9ece6a'
      - '#e0af68'
      - '#7aa2f7'
      - '#bb9af7'
      - '#7dcfff'
      - '#c0caf5'
  font: Maple Mono Normal NF CN
  customColorSchemes:
    - name: ayu
      foreground: '#e6e1cf'
      background: '#0f1419'
      cursor: '#f29718'
      colors:
        - '#000000'
        - '#ff3333'
        - '#b8cc52'
        - '#e7c547'
        - '#36a3d9'
        - '#f07178'
        - '#95e6cb'
        - '#ffffff'
        - '#323232'
        - '#ff6565'
        - '#eafe84'
        - '#fff779'
        - '#68d5ff'
        - '#ffa3aa'
        - '#c7fffd'
        - '#ffffff'
  unicode: 9
  profile: local:custom:Pwsh:9215613a-dd5a-4924-8406-08871f68b001
  showBuiltinProfiles: false
  fallbackFont: FiraCode Nerd Font Mono
  fontWeightBold: 600
  ligatures: true
  fontSize: 16
  frontend: xterm
ssh: {}
clickableLinks:
  modifier: ctrlKey
accessibility: {}
appearance:
  opacity: 0.98
  spaciness: 0.8
  colorSchemeMode: auto
hacks: {}
providerBlacklist: []
commandBlacklist: []
enableWelcomeTab: false
pluginBlacklist:
  - title-control
  - tabbyspaces
  - backslash-newline
  - highlight
profileDefaults:
  ssh:
    disableDynamicTitle: true
profileBlacklist: []
language: zh-TW
qc:
  cmds:
    - name: ls
      text: ls
      appendCR: false
      group: Test
      shortcut: Shift+D
profiles:
  - type: local
    icon: >-
      <svg viewBox="0 0 120 90.001"
      xmlns="http://www.w3.org/2000/svg"><linearGradient id="1652546273"
      x1="95.267" x2="26.7" y1="91.926" y2="30.68"
      gradientTransform="translate(-4.002 -19)"
      gradientUnits="userSpaceOnUse"><stop stop-color="#A9C8FF"
      offset="0"></stop><stop stop-color="#C7E6FF"
      offset="1"></stop></linearGradient><path d="M5.03 90c-1.632
      0-3.045-.638-3.977-1.798-.952-1.185-1.28-2.814-.896-4.47L18.143
      5.821C18.897 2.557 22.06 0 25.347 0h89.623c1.634 0 3.047.638 3.978
      1.798.952 1.184 1.279 2.814.896 4.47l-17.986 77.911c-.753 3.264-3.917
      5.822-7.203 5.822H5.03z" clip-rule="evenodd" fill="url(#1652546273)"
      fill-rule="evenodd" opacity=".8"></path><g transform="translate(-4.002
      -19)"><linearGradient id="1652546298" x1="26.585" x2="93.585" y1="30.778"
      y2="90.278" gradientUnits="userSpaceOnUse"><stop stop-color="#2D4664"
      offset="0"></stop><stop stop-color="#29405B" offset=".169"></stop><stop
      stop-color="#1E2F43" offset=".445"></stop><stop stop-color="#0C131B"
      offset=".79"></stop><stop offset="1"></stop></linearGradient><path
      d="M118.5 20H29.634c-2.769 0-5.53 2.259-6.168 5.045l-17.834 77.91C4.995
      105.742 6.722 108 9.491 108h88.865c2.769 0 5.53-2.258
      6.168-5.045l17.834-77.911c.638-2.785-1.09-5.044-3.858-5.044z"
      clip-rule="evenodd" fill="url(#1652546298)"
      fill-rule="evenodd"></path></g><g clip-rule="evenodd"
      fill-rule="evenodd"><path d="M60.163 68.558h21.613c2.513 0 4.55 2.125 4.55
      4.746s-2.037 4.747-4.55 4.747H60.163c-2.513 0-4.55-2.125-4.55-4.747
      0-2.621 2.037-4.746 4.55-4.746zM74.182 47.455c-.372.749-1.144 1.575-2.509
      2.534L31.56 78.798c-2.19 1.591-5.334
      1.001-7.021-1.319s-1.28-5.49.91-7.082l36.173-26.194v-.538L38.894
      19.487c-1.854-1.972-1.661-5.161.431-7.124 2.092-1.962 5.29-1.954
      7.144.018L73.74 41.393c1.548 1.647 1.663 4.141.442 6.062z"
      fill="#2c5591"></path><path d="M73.182 46.455c-.372.749-1.144 1.575-2.509
      2.534L30.56 77.798c-2.19 1.591-5.334
      1.001-7.021-1.319s-1.28-5.49.91-7.082l36.173-26.194v-.538L37.894
      18.487c-1.854-1.972-1.661-5.161.431-7.124 2.092-1.962 5.29-1.954
      7.144.018L72.74 40.393c1.548 1.647 1.663 4.141.442 6.062zM59.548
      68h21.613c2.513 0 4.55 2.015 4.55 4.5s-2.037 4.5-4.55 4.5H59.548c-2.513
      0-4.55-2.015-4.55-4.5s2.037-4.5 4.55-4.5z" fill="#fff"></path></g></svg>
    options:
      command: C:\Program Files\PowerShell\7\pwsh.exe
      args:
        - '-nologo'
      env:
        WT_SESSION: 0
      runAsAdministrator: true
    name: Pwsh(Admin)
    id: local:custom:Pwsh(Admin):b5f707fb-24a8-4730-aeec-8cfe06639b72
  - type: local
    name: Pwsh
    icon: >-
      <svg viewBox="0 0 120 90.001"
      xmlns="http://www.w3.org/2000/svg"><linearGradient id="1652546273"
      x1="95.267" x2="26.7" y1="91.926" y2="30.68"
      gradientTransform="translate(-4.002 -19)"
      gradientUnits="userSpaceOnUse"><stop stop-color="#A9C8FF"
      offset="0"></stop><stop stop-color="#C7E6FF"
      offset="1"></stop></linearGradient><path d="M5.03 90c-1.632
      0-3.045-.638-3.977-1.798-.952-1.185-1.28-2.814-.896-4.47L18.143
      5.821C18.897 2.557 22.06 0 25.347 0h89.623c1.634 0 3.047.638 3.978
      1.798.952 1.184 1.279 2.814.896 4.47l-17.986 77.911c-.753 3.264-3.917
      5.822-7.203 5.822H5.03z" clip-rule="evenodd" fill="url(#1652546273)"
      fill-rule="evenodd" opacity=".8"></path><g transform="translate(-4.002
      -19)"><linearGradient id="1652546298" x1="26.585" x2="93.585" y1="30.778"
      y2="90.278" gradientUnits="userSpaceOnUse"><stop stop-color="#2D4664"
      offset="0"></stop><stop stop-color="#29405B" offset=".169"></stop><stop
      stop-color="#1E2F43" offset=".445"></stop><stop stop-color="#0C131B"
      offset=".79"></stop><stop offset="1"></stop></linearGradient><path
      d="M118.5 20H29.634c-2.769 0-5.53 2.259-6.168 5.045l-17.834 77.91C4.995
      105.742 6.722 108 9.491 108h88.865c2.769 0 5.53-2.258
      6.168-5.045l17.834-77.911c.638-2.785-1.09-5.044-3.858-5.044z"
      clip-rule="evenodd" fill="url(#1652546298)"
      fill-rule="evenodd"></path></g><g clip-rule="evenodd"
      fill-rule="evenodd"><path d="M60.163 68.558h21.613c2.513 0 4.55 2.125 4.55
      4.746s-2.037 4.747-4.55 4.747H60.163c-2.513 0-4.55-2.125-4.55-4.747
      0-2.621 2.037-4.746 4.55-4.746zM74.182 47.455c-.372.749-1.144 1.575-2.509
      2.534L31.56 78.798c-2.19 1.591-5.334
      1.001-7.021-1.319s-1.28-5.49.91-7.082l36.173-26.194v-.538L38.894
      19.487c-1.854-1.972-1.661-5.161.431-7.124 2.092-1.962 5.29-1.954
      7.144.018L73.74 41.393c1.548 1.647 1.663 4.141.442 6.062z"
      fill="#2c5591"></path><path d="M73.182 46.455c-.372.749-1.144 1.575-2.509
      2.534L30.56 77.798c-2.19 1.591-5.334
      1.001-7.021-1.319s-1.28-5.49.91-7.082l36.173-26.194v-.538L37.894
      18.487c-1.854-1.972-1.661-5.161.431-7.124 2.092-1.962 5.29-1.954
      7.144.018L72.74 40.393c1.548 1.647 1.663 4.141.442 6.062zM59.548
      68h21.613c2.513 0 4.55 2.015 4.55 4.5s-2.037 4.5-4.55 4.5H59.548c-2.513
      0-4.55-2.015-4.55-4.5s2.037-4.5 4.55-4.5z" fill="#fff"></path></g></svg>
    options:
      command: C:\Program Files\PowerShell\7\pwsh.exe
      args:
        - '-nologo'
      env:
        WT_SESSION: 0
      cwd: C:\Users\TC
    id: local:custom:Pwsh:9215613a-dd5a-4924-8406-08871f68b001
workspaceManager: {}
titleControl: {}
charsetPlugin:
  perSessionCharsetMap:
    - sessionId: local:custom:Pwsh:9215613a-dd5a-4924-8406-08871f68b001
      charset:
        name: UTF-8
        charset: utf-8
backslashNewline: {}
tabbyspaces:
  workspaces: []
highlightPlugin:
  advanced: {}
  highlightProfiles:
    - id: 60606be0-c0ff-42bc-bf77-de8a2435447f
      name: Default
      keywords:
        - text: ERROR
          enabled: true
          background: true
          backgroundColor: '1'
        - text: WARN
          enabled: true
          background: true
          backgroundColor: '3'
        - text: INFO
          enabled: true
          background: true
          backgroundColor: '6'
        - text: 错误
          enabled: true
          background: true
          backgroundColor: '1'
        - text: 警告
          enabled: true
          background: true
          backgroundColor: '3'
        - text: 信息
          enabled: true
          background: true
          backgroundColor: '6'
  replaceProfiles:
    - id: 986666dd-dac9-4c7a-a295-9b4aff66abdd
      name: Default
      patterns:
        - enabled: true
          search: ERROR
          replace: 出错啦
        - enabled: true
          search: WARN
          replace: 警告警告
  highlightEnabled: true
qs: {}
ogAutoCompletePlugin:
  ai: {}
  appearance: {}
  history: {}
  arguments: {}
syncConfig: {}
